blank_issues_enabled: true
contact_links:
  - name: 機能改善・新機能(RUNTEQアプリ)
    about: RUNTEQ開発Projectに紐づく機能改善・新機能用のテンプレート
    url: https://github.com/startup-technology/runteq/issues/new?template=feature_request.md&projects=startup-technology/10
