default: &default
  adapter: 'postgresql'
  encoding: 'unicode'
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: 'app_development'
  host: 'db'
  username: 'postgres'
  password: 'password'

test:
  <<: *default
  database: 'app_test'
  host: 'db'
  username: 'postgres'
  password: 'password'

production:
  <<: *default
  database: 'board_app_production'
  url: <%= Rails.application.credentials.dig(:production, :database_url) %>
  # host: 'db'
  # username: 'postgres'
  # password: 'password'

